# ### Here is a sample to enable amp on controller actions
# ### enable amp on users all actions
# rails_amp:
#   users:
#
# ### enable amp on users#index, users#show, posts#index, posts#show
# ### controller_name: action1 action2 action3 ...
# rails_amp:
#   users: index show
#   posts: index show
#
# ### enable amp on all controllers and actions
# rails_amp:
#   application:
#
# ### disable amp
# rails_amp:
#
rails_amp:
  home: index about
